name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          # some arbitrary distribution selected
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        # -B means: batch-mode (no questions, no progress-related log pollution)
        # coverage profile is needed for test coverage for sonar
        run: mvn test -Pcoverage -B
  sonar:
    runs-on: ubuntu-latest
    # carries Sonar secret
    environment: CI
    env:
      # The SonarScanner for Maven automatically picks up the value directly from the environment variable.
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          # unlimited fetch depth for Sonar
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          # some arbitrary distribution selected
          distribution: 'temurin'
          cache: maven
      - name: Run Sonar analyzing
        # Sonar would require extra preparations
        run: mvn sonar:sonar \
          -Dsonar.projectKey=leokom-chess \ 
          -Dsonar.organization=lrozenblyum-github
