name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          # some arbitrary distribution selected
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        # -B means: batch-mode (no questions, no progress-related log pollution)
        # coverage profile is needed for test coverage for sonar
        run: mvn test -Pcoverage -B
      - name: Run Sonar analyzing
        # Sonar would require extra preparations
        run: mvn sonar:sonar -Dsonar.projectKey=leokom-chess
