name: CI

on:
  push:
    branches:
      - master
      - release/**
      - long-lived/**
  pull_request:

jobs:
  CI_Sonar:
    # carries Sonar secret
    environment: CI
    env:
      # The SonarScanner for Maven automatically picks up the value directly from the environment variable.
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # According to Sonar: Needed to get PR information, if any
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # unlimited fetch depth for Sonar
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          # some arbitrary distribution selected
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        # -B means: batch-mode (no questions, no progress-related log pollution)
        # coverage profile is needed for test coverage for sonar
        run: mvn test -Pcoverage -B
      - name: Run Sonar analyzing
        # specified the project key explicitly because I didn't like the automatically generate Maven-based name (com.leokom:chess)
        # thanks to this explicit specification we're free to change Maven coordinates
        # the organization key was found here: https://sonarcloud.io/account/organizations
        run: mvn sonar:sonar
          -Dsonar.projectKey=leokom-chess 
          -Dsonar.organization=lrozenblyum-github
          -Dsonar.host.url=https://sonarcloud.io
